# load_existing_data function and static facility data

# This is from the earlier AI scrape which lets us have a solid basis to work with.
# Generated circa August 23, 2025 and subject to falling out of date.
# Adams County is actually on Hobo Fork Road, that is ICE's typo.


def load_existing_data():
    # Static list or file reading logic
    # @formatter:off
    # this prevents hard wrap.
    facilities_data = [
        # Page 0 (original data)
        {
            "name": "Abyon | Farmville Detention Center",
            "field_office": "Washington Field Office",
            "address": "508 Waterworks Road, Farmville, VA 23901, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Adams County Correctional Center",
            "field_office": "New Orleans Field Office",
            "address": "20 Hobo Forks Road, Natchez, MS 39120, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Adelanto ICE Processing Center",
            "field_office": "Los Angeles Field Office",
            "address": "Adelanto East 10400 Rancho Road | Adelanto West 10250 Rancho Road, Adelanto, CA 92301, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Alamance County Detention Center",
            "field_office": "Atlanta Field Office",
            "address": "109 South Maple Street, Graham, NC 27253, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Allen Parish Public Safety Complex",
            "field_office": "New Orleans Field Office",
            "address": "7340 Highway 26 W, Oberlin, LA 70655, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Baker County Detention Center",
            "field_office": "Miami Field Office",
            "address": "1 Sheriff's Office Drive, MacClenny, FL 32063, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Bluebonnet Detention Facility",
            "field_office": "Dallas Field Office",
            "address": "400 2nd Street, Anson, TX 79501, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Boone County Jail",
            "field_office": "Chicago Field Office",
            "address": "3020 Conrad Lane, Burlington, KY 41005, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Broward Transitional Center",
            "field_office": "Miami Field Office",
            "address": "3900 N. Powerline Road, Pompano Beach, FL 33073, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Buffalo (Batavia) Service Processing Center",
            "field_office": "Buffalo Field Office",
            "address": "4250 Federal Drive, Batavia, NY 14020, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Butler County Sheriff's Office",
            "field_office": "Detroit Field Office",
            "address": "705 Hanover Street, Hamilton, OH 45011, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Calhoun County Correctional Center",
            "field_office": "Detroit Field Office",
            "address": "185 E. Michigan Street, Battle Creek, MI 49014, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Campbell County Detention Center",
            "field_office": "Chicago Field Office",
            "address": "601 Central Avenue, Newport, KY 41071, United States",
            "phone": "(859) 431-4611",
            "image_url": "",
        },
        {
            "name": "Caroline Detention Facility",
            "field_office": "Washington Field Office",
            "address": "11093 SW Lewis Memorial Dr, Bowling Green, VA 22427, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Central Arizona Florence Correctional Center",
            "field_office": "Phoenix Field Office",
            "address": "1100 Bowling Road, Florence, AZ 85132, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Central Louisiana ICE Processing Center",
            "field_office": "New Orleans Field Office",
            "address": "830 Pine Hill Road, Jena, LA 71342, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Chase County Jail",
            "field_office": "Chicago Field Office",
            "address": "301 South Walnut, Cottonwood Falls, KS 66845, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Chippewa County Correctional Facility",
            "field_office": "Detroit Field Office",
            "address": "325 Court Street, Sault Ste. Marie, MI 49783, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Cibola County Correctional Center",
            "field_office": "El Paso Field Office",
            "address": "2000 Cibola Loop, Milan, NM 87021, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Clark County Jail",
            "field_office": "Chicago Field Office",
            "address": "501 E Court Avenue, Suite 159, Jeffersonville, IN 47130, United States",
            "phone": "",
            "image_url": "",
        },
        # Page 1
        {
            "name": "Cimarron Correctional Facility",
            "field_office": "Dallas Field Office",
            "address": "3200 S. Kings Hwy, Cushing, OK 74023, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Clay County Jail",
            "field_office": "Chicago Field Office",
            "address": "611 East Jackson Street, Brazil, IN 47834, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Clinton County Correctional Facility",
            "field_office": "Philadelphia Field Office",
            "address": "58 Pine Mountain Road, McElhattan, PA 17748, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Clinton County Jail",
            "field_office": "Buffalo Field Office",
            "address": "25 McCarthy Drive, Plattsburgh, NY 12901, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Clinton County Sheriff's Office",
            "field_office": "Chicago Field Office",
            "address": "301 E Walnut Street, Frankfort, IN 46041, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "CNMI Department of Corrections",
            "field_office": "San Francisco Field Office",
            "address": "Vincente Taman Building, PO Box 506506, Susupe, Saipan, MP 96950, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Coastal Bend Detention Center",
            "field_office": "Harlingen Field Office",
            "address": "4909 Farm to Market Road, Robstown, TX 78380, United States",
            "phone": "(361) 767-3400",
            "image_url": "",
        },
        {
            "name": "CoreCivic Laredo Processing Center",
            "field_office": "Harlingen Field Office",
            "address": "4702 East Saunders, Laredo, TX 78401, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "CoreCivic Webb County Detention Center",
            "field_office": "Harlingen Field Office",
            "address": "9998 S. Highway 83, Laredo, TX 78046, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Corrections Center of Northwest Ohio (CCNO)",
            "field_office": "Detroit Field Office",
            "address": "03151 Co. Rd. 24.2, Stryker, OH 43557, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Cumberland County Jail",
            "field_office": "Boston Field Office",
            "address": "50 County Way, Portland, ME 04102, United States",
            "phone": "(207) 774-5939",
            "image_url": "",
        },
        {
            "name": "Delaney Hall Detention Facility",
            "field_office": "Newark Field Office",
            "address": "451 Doremus Avenue, Newark, NJ 07105, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Denver Contract Detention Facility (Aurora)",
            "field_office": "Denver Field Office",
            "address": "3130 North Oakland Street, Aurora, CO 80010, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Desert View Annex",
            "field_office": "Los Angeles Field Office",
            "address": "10450 Rancho Road, Adelanto, CA 92301, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Dilley Immigration Processing Center",
            "field_office": "San Antonio Field Office",
            "address": "300 El Rancho Way, Dilley, TX 78017, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Dodge Detention Facility",
            "field_office": "Chicago Field Office",
            "address": "216 W. Center Street, Juneau, WI 53039, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "East Hidalgo Detention Center",
            "field_office": "Harlingen Field Office",
            "address": "1300 E Hwy 107, La Villa, TX 78562, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Eden Detention Center",
            "field_office": "Dallas Field Office",
            "address": "704 E Broadway Street, Eden, TX 76837, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "El Paso Service Processing Center",
            "field_office": "El Paso Field Office",
            "address": "8915 Montana Avenue, El Paso, TX 79925, United States",
            "phone": "",
            "image_url": "",
        },
        # Page 2
        {
            "name": "El Valle Detention Facility",
            "field_office": "Harlingen Field Office",
            "address": "1800 Industrial Drive, Raymondville, TX 78580, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Elizabeth Contract Detention Facility",
            "field_office": "Newark Field Office",
            "address": "625 Evans Street, Elizabeth, NJ 07201, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Elmore County Detention Center (Elmore County Jail)",
            "field_office": "Salt Lake City Field Office",
            "address": "2255 East 8th North, Mountain Home, ID 83647, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Eloy Detention Center",
            "field_office": "Phoenix Field Office",
            "address": "1705 E Hanna Rd, Eloy, AZ 85131, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "FCI Atlanta",
            "field_office": "Atlanta Field Office",
            "address": "601 McDonough Blvd SE, Atlanta, GA 30315, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "FCI Leavenworth",
            "field_office": "Chicago Field Office",
            "address": "1300 Metropolitan, Leavenworth, KS 66048, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "FDC Miami",
            "field_office": "Miami Field Office",
            "address": "33 NE 4th Street, Miami, FL 33132, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "FDC Philadelphia",
            "field_office": "Philadelphia Field Office",
            "address": "700 Arch Street, Philadelphia, PA 19106, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Federal Correctional Institution - Berlin, NH",
            "field_office": "Boston Field Office",
            "address": "1 Success Loop Rd, Berlin, NH 03570, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Federal Detention Center, Honolulu (FDC Honolulu)",
            "field_office": "San Francisco Field Office",
            "address": "351 Elliott Street, Honolulu, HI 96819, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Florence Service Processing Center",
            "field_office": "Phoenix Field Office",
            "address": "3250 N. Pinal Parkway, Florence, AZ 85132, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Folkston ICE Processing Center (Annex)",
            "field_office": "Atlanta Field Office",
            "address": "3424 Hwy 252 E, P.O. Box 248, Folkston, GA 31537, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Folkston ICE Processing Center (Main)",
            "field_office": "Atlanta Field Office",
            "address": "3026 Hwy 252 East, PO Box 248, Folkston, GA 31537, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Freeborn County Jail Services",
            "field_office": "St. Paul Field Office",
            "address": "411 S. Broadway Avenue, Albert Lea, MN 56007, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Geauga County Safety Center",
            "field_office": "Detroit Field Office",
            "address": "12450 Merritt Road, Chardon, OH 44024, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Glades County Detention Center",
            "field_office": "Miami Field Office",
            "address": "1297 East SR 78, Moore Haven, FL 33471, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Golden State Annex",
            "field_office": "San Francisco Field Office",
            "address": "611 Frontage Road, McFarland, CA 93250, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Grand Forks County Correctional Center",
            "field_office": "St. Paul Field Office",
            "address": "1701 North Washington, Grand Forks, ND 58203, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Grayson County Detention Center",
            "field_office": "Chicago Field Office",
            "address": "320 Shaw Station Road, Leachfield, KY 42754, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Greene County Jail",
            "field_office": "Chicago Field Office",
            "address": "1199 N Haseltine Road, Springfield, MO 65802, United States",
            "phone": "(417) 868-4040",
            "image_url": "",
        },
        # Page 3
        {
            "name": "Guam Department of Corrections, Hagatna Detention Facility",
            "field_office": "San Francisco Field Office",
            "address": "203 Aspinall Avenue, Hagatna, GU 96910, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Henderson Detention Center",
            "field_office": "Salt Lake City Field Office",
            "address": "18 E. Basic Road, Henderson, NV 89015, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Hopkins County Jail",
            "field_office": "Chicago Field Office",
            "address": "2250 Laffoon Trl, Madisonville, KY 42431, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Houston Contract Detention Facility",
            "field_office": "Houston Field Office",
            "address": "15850 Export Plaza Drive, Houston, TX 77032, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "IAH Polk Adult Detention Facility",
            "field_office": "Houston Field Office",
            "address": "3400 FM 350 South, Livingston, TX 77351, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Imperial Regional Detention Facility",
            "field_office": "San Diego Field Office",
            "address": "1572 Gateway Road, Calexico, CA 92231, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Jackson Parish Correctional Center",
            "field_office": "New Orleans Field Office",
            "address": "287 Industrial Drive, Jonesboro, LA 71251, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Joe Corley Processing Center",
            "field_office": "Houston Field Office",
            "address": "500 Hilbig Road, Conroe, TX 77301, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Kandiyohi County Jail",
            "field_office": "St. Paul Field Office",
            "address": "2201 23rd St. NE, Willmar, MN 56201, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Karnes County Immigration Processing Center",
            "field_office": "San Antonio Field Office",
            "address": "409 FM 1144, Karnes City, TX 78118, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Kay County Detention Center",
            "field_office": "Chicago Field Office",
            "address": "1101 West Dry Road, Newkirk, OK 74647, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Krome North Service Processing Center",
            "field_office": "Miami Field Office",
            "address": "18201 SW 12th Street, Miami, FL 33194, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "La Salle County Regional Detention Center",
            "field_office": "San Antonio Field Office",
            "address": "832 East Texas HWY 44, Encinal, TX 78019, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Limestone County Detention Center",
            "field_office": "Houston Field Office",
            "address": "910 North Tyus Street, Groesbeck, TX 76642, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Mahoning County Justice Center",
            "field_office": "Detroit Field Office",
            "address": "110 Fifth Avenue, Youngstown, OH 44503, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "MDC Brooklyn",
            "field_office": "New York City Field Office",
            "address": "80 29th Street, Brooklyn, NY 11232, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Mesa Verde ICE Processing Center",
            "field_office": "San Francisco Field Office",
            "address": "425 Golden State Avenue, Bakersfield, CA 93301, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Monroe County Jail",
            "field_office": "Detroit Field Office",
            "address": "7000 East Dunbar Road, Monroe, MI 48161, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Montgomery Processing Center",
            "field_office": "Houston Field Office",
            "address": "806 Hilbig Road, Conroe, TX 77301, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Moshannon Valley Processing Center",
            "field_office": "Philadelphia Field Office",
            "address": "555 GEO Drive, Philipsburg, PA 16866, United States",
            "phone": "",
            "image_url": "",
        },
        # Page 4
        {
            "name": "Naval Station Guantanamo Bay (JTF Camp Six and Migrant Ops Center Main A)",
            "field_office": "Miami Field Office",
            "address": "",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Nevada Southern Detention Center",
            "field_office": "Salt Lake City Field Office",
            "address": "2190 E Mesquite Avenue, Pahrump, NV 89048, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "North Lake Processing Center",
            "field_office": "Detroit Field Office",
            "address": "1805 W 32nd Street, Baldwin, MI 49304, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Northeast Ohio Correctional Center",
            "field_office": "Detroit Field Office",
            "address": "2240 Hubbard Road, Youngstown, OH 44505, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Northwest ICE Processing Center (NWIPC)",
            "field_office": "Seattle Field Office",
            "address": "1623 E J Street, Suite 2, Tacoma, WA 98421-1615, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Oldham County Detention Center",
            "field_office": "Chicago Field Office",
            "address": "3405 West Highway 146, LaGrange, KY 40031, United States",
            "phone": "(502) 222-3500",
            "image_url": "",
        },
        {
            "name": "Orange County Jail",
            "field_office": "New York City Field Office",
            "address": "110 Wells Farm Road, Goshen, NY 10924, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Otay Mesa Detention Center",
            "field_office": "San Diego Field Office",
            "address": "7488 Calzada de la Fuente, San Diego, CA 92154, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Otero County Processing Center",
            "field_office": "El Paso Field Office",
            "address": "26 McGregor Range Road, Chaparral, NM 88081, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Pennington County Jail",
            "field_office": "St. Paul Field Office",
            "address": "307 Saint Joseph St, Rapid City, SD 57701, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Phelps County Jail",
            "field_office": "St. Paul Field Office",
            "address": "715 5th Avenue, Holdrege, NE 68949, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Phelps County Jail",
            "field_office": "Chicago Field Office",
            "address": "500 W. 2nd Street, Rolla, MO 65401, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Pike County Correctional Facility",
            "field_office": "Philadelphia Field Office",
            "address": "175 Pike County Blvd., Lords Valley, PA 18428, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Pine Prairie ICE Processing Center",
            "field_office": "New Orleans Field Office",
            "address": "1133 Hampton Dupre Road, Pine Prairie, LA 70576, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Plymouth County Correctional Facility",
            "field_office": "Boston Field Office",
            "address": "26 Long Pond Road, Plymouth, MA 02360, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Polk County Jail",
            "field_office": "St. Paul Field Office",
            "address": "1985 NE 51st Place, Des Moines, IA 50313, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Port Isabel Service Processing Center",
            "field_office": "Harlingen Field Office",
            "address": "27991 Buena Vista Blvd., Los Fresnos, TX 78566, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Pottawattamie County Jail",
            "field_office": "St. Paul Field Office",
            "address": "1400 Big Lake Road, Council Bluffs, IA 51501, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Prairieland Detention Facility",
            "field_office": "Dallas Field Office",
            "address": "1209 Sunflower Lane, Alvarado, TX 76009, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Richwood Correctional Center",
            "field_office": "New Orleans Field Office",
            "address": "180 Pine Bayou Circle, Monroe, LA 71202, United States",
            "phone": "",
            "image_url": "",
        },
        # Page 5
        {
            "name": "Rio Grande Processing Center",
            "field_office": "Harlingen Field Office",
            "address": "1001 San Rio Blvd, Laredo, TX 78046, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "River Correctional Center",
            "field_office": "New Orleans Field Office",
            "address": "26362 Highway 15, Ferriday, LA 71334, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Rolling Plains Detention Center",
            "field_office": "Dallas Field Office",
            "address": "118 County Road 206, Haskell, TX 79521, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "San Luis Regional Detention Center",
            "field_office": "San Diego Field Office",
            "address": "406 North Avenue D, San Luis, AZ 85349, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Seneca County Jail",
            "field_office": "Detroit Field Office",
            "address": "3040 South State Route 100, Tiffin, OH 44883, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Sherburne County Jail Services",
            "field_office": "St. Paul Field Office",
            "address": "13880 Business Center Drive NW, Elk River, MN 55330, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "South Louisiana ICE Processing Center",
            "field_office": "New Orleans Field Office",
            "address": "3843 Stagg Ave, Basile, LA 70515, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "South Texas ICE Processing Center",
            "field_office": "San Antonio Field Office",
            "address": "566 Veterans Drive, Pearsall, TX 78061, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "St. Clair County Jail",
            "field_office": "Detroit Field Office",
            "address": "1170 Michigan Road, Port Huron, MI 48060, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Ste. Genevieve County Detention Center",
            "field_office": "Chicago Field Office",
            "address": "5 Basler Drive, Ste. Genevieve, MO 63670, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Stewart Detention Center",
            "field_office": "Atlanta Field Office",
            "address": "146 CCA Road, Lumpkin, GA 31815, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Strafford County Corrections",
            "field_office": "Boston Field Office",
            "address": "266 County Farm Road, Dover, NH 03820, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Sweetwater County Detention Center",
            "field_office": "Denver Field Office",
            "address": "50140 US Highway 191 South, Rock Springs, WY 82901, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "T. Don Hutto Detention Center",
            "field_office": "San Antonio Field Office",
            "address": "1001 Welch Street, Taylor, TX 76574, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Torrance County Detention Facility",
            "field_office": "El Paso Field Office",
            "address": "209 County Road A049, Estancia, NM 87016, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Washoe County Jail",
            "field_office": "Salt Lake City Field Office",
            "address": "911 E Parr Blvd, Reno, NV 89512, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Winn Correctional Center",
            "field_office": "New Orleans Field Office",
            "address": "560 Gum Springs Road, Winnfield, LA 71483, United States",
            "phone": "",
            "image_url": "",
        },
        {
            "name": "Wyatt Detention Facility",
            "field_office": "Boston Field Office",
            "address": "950 High Street, Central Falls, RI 02863, United States",
            "phone": "",
            "image_url": "",
        },
    ]
    return facilities_data
