# load_existing_data function and static facility data


facilities_data = {
    "enrich_runtime": 0,
    "facilities": {
        "12501 GATEWAY BLVD S,EL PASO,TX,79934": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "TX",
                "country": "",
                "locality": "EL PASO",
                "postal_code": 79934,
                "street": "12501 GATEWAY BLVD S",
            },
            "avg_stay_length": 4.6051766051766,
            "facility_type": "STAGING",
            "field_office": "",
            "image_url": "",
            "inspection_date": None,
            "name": "EL PASO SOFT SIDED FACILITY",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 3.58255451713394, "non_criminal": 12.3364485981307},
                "male": {"allowed": True, "criminal": 57.4423676012446, "non_criminal": 134.909657320886},
            },
            "raw_scrape": "",
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "1300 LANGE CT,BARABOO,WI,53913": {
            "_repaired_record": True,
            "address": {
                "administrative_area": "WI",
                "country": "",
                "locality": "BARABOO",
                "postal_code": 53913,
                "street": "1300 LANGE CT.",
            },
            "avg_stay_length": 6.875,
            "facility_type": "USMS IGA",
            "field_office": "",
            "image_url": "",
            "inspection_date": None,
            "name": "SAUK COUNTY SHERIFF",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 0.0, "non_criminal": 0.00623052959501558},
                "male": {"allowed": True, "criminal": 0.59190031152648, "non_criminal": 1.07165109034268},
            },
            "raw_scrape": "",
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "1623 E J STREET,TACOMA,WA,98421": {
            "_repaired_record": True,
            "address": {
                "administrative_area": "WA",
                "country": "United States",
                "locality": "Tacoma",
                "postal_code": "98421-1615",
                "street": "1623 E J Street, Suite 2",
            },
            "avg_stay_length": 68.9292759201347,
            "facility_type": "CDF",
            "field_office": "Seattle Field Office",
            "image_url": "https://www.ice.gov/sites/default/files/images/nwIPC.png",
            "inspection_date": "2025-01-30",
            "name": "NORTHWEST ICE PROCESSSING CENTER",
            "page_updated_date": "2025-08-20 07:47:00+04:00",
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 45.6323987538941, "non_criminal": 78.5451713395638},
                "male": {"allowed": True, "criminal": 403.180685358257, "non_criminal": 627.056074766356},
            },
            "raw_scrape": "PGxpIGNsYXNzPSJncmlkIj48ZGl2IGNsYXNzPSJncmlkX19jb250ZW50Ij48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1pbWFnZS1maWxlIj48ZGl2IGNsYXNzPSJmaWVsZC1jb250ZW50Ij48aW1nIGFsdD0iIiBzcmM9Ii9zaXRlcy9kZWZhdWx0L2ZpbGVzL2ltYWdlcy9ud0lQQy5wbmciLz48L2Rpdj48L2Rpdj48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC10aXRsZSI+PHNwYW4gY2xhc3M9ImZpZWxkLWNvbnRlbnQiPk5vcnRod2VzdCBJQ0UgUHJvY2Vzc2luZyBDZW50ZXIgKE5XSVBDKTwvc3Bhbj48L2Rpdj48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1maWVsZC1vZmZpY2UtbmFtZSI+PGRpdiBjbGFzcz0iZmllbGQtY29udGVudCI+U2VhdHRsZSBGaWVsZCBPZmZpY2U8L2Rpdj48L2Rpdj48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1kZXRlbnRpb24tZmFjaWxpdHktbG9jYXRpbyI+PGRpdiBjbGFzcz0iZmllbGQtY29udGVudCI+PHAgY2xhc3M9ImFkZHJlc3MiIHRyYW5zbGF0ZT0ibm8iPjxzcGFuIGNsYXNzPSJhZGRyZXNzLWxpbmUxIj4xNjIzIEUgSiBTdHJlZXQsIFN1aXRlIDI8L3NwYW4+PGJyLz4KPHNwYW4gY2xhc3M9ImxvY2FsaXR5Ij5UYWNvbWE8L3NwYW4+LCA8c3BhbiBjbGFzcz0iYWRtaW5pc3RyYXRpdmUtYXJlYSI+V0E8L3NwYW4+IDxzcGFuIGNsYXNzPSJwb3N0YWwtY29kZSI+OTg0MjEtMTYxNTwvc3Bhbj48YnIvPgo8c3BhbiBjbGFzcz0iY291bnRyeSI+VW5pdGVkIFN0YXRlczwvc3Bhbj48YnIvPjxzcGFuIGNsYXNzPSJjdC1hZGRyIj48L3NwYW4+PC9wPjwvZGl2PjwvZGl2PjxkaXYgY2xhc3M9InZpZXdzLWZpZWxkIHZpZXdzLWZpZWxkLXRpdGxlLTEiPjxzcGFuIGNsYXNzPSJmaWVsZC1jb250ZW50Ij48YSBocmVmPSIvZGV0YWluL2RldGVudGlvbi1mYWNpbGl0aWVzL25vcnRod2VzdC1pY2UtcHJvY2Vzc2luZy1jZW50ZXItbndpcGMiIGhyZWZsYW5nPSJlbiI+Tm9ydGh3ZXN0IElDRSBQcm9jZXNzaW5nIENlbnRlciAoTldJUEMpPC9hPjwvc3Bhbj48L2Rpdj48L2Rpdj4KPC9saT4=",
            "source_urls": [
                "https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx",
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=4",
                "https://www.ice.gov/detain/detention-facilities/northwest-ice-processing-center-nwipc",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "216 S BROAD ST,GUTHRIE,OK,73044": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "OK",
                "country": "",
                "locality": "GUTHRIE",
                "postal_code": 73044,
                "street": "216 S BROAD ST",
            },
            "avg_stay_length": 2.69458128078818,
            "facility_type": "USMS IGA",
            "field_office": "",
            "image_url": "",
            "inspection_date": "2025-05-13",
            "name": "LOGAN COUNTY JAIL",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": False, "criminal": 0.0467289719626168, "non_criminal": 0.158878504672897},
                "male": {"allowed": False, "criminal": 0.551401869158878, "non_criminal": 1.16510903426791},
            },
            "raw_scrape": "",
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "219 EAST FREMONT AVENUE,RIGBY,ID,83442": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "ID",
                "country": "",
                "locality": "RIGBY",
                "postal_code": 83442,
                "street": "219 EAST FREMONT AVENUE",
            },
            "avg_stay_length": 2.86121673003802,
            "facility_type": "IGSA",
            "field_office": "",
            "image_url": "",
            "inspection_date": "2024-07-18",
            "name": "JEFFERSON COUNTY JAIL",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 0.0311526479750779, "non_criminal": 0.0249221183800623},
                "male": {"allowed": True, "criminal": 3.56386292834889, "non_criminal": 1.22118380062305},
            },
            "raw_scrape": "",
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "320 SHAW STATION ROAD,LEITCHFIELD,KY,42754": {
            "_repaired_record": True,
            "address": {
                "administrative_area": "KY",
                "country": "United States",
                "locality": "Leachfield",
                "postal_code": "42754",
                "street": "320 Shaw Station Road",
            },
            "avg_stay_length": 16.1679626749611,
            "facility_type": "USMS IGA",
            "field_office": "Chicago Field Office",
            "image_url": "https://www.ice.gov/sites/default/files/2025-08/detFacGrayson.jpg",
            "inspection_date": "2025-08-21",
            "name": "GRAYSON COUNTY JAIL",
            "page_updated_date": "2025-08-20 08:07:50+04:00",
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 19.7383177570094, "non_criminal": 36.9844236760124},
                "male": {"allowed": True, "criminal": 5.07165109034266, "non_criminal": 2.83800623052959},
            },
            "raw_scrape": "PGxpIGNsYXNzPSJncmlkIj48ZGl2IGNsYXNzPSJncmlkX19jb250ZW50Ij48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1pbWFnZS1maWxlIj48ZGl2IGNsYXNzPSJmaWVsZC1jb250ZW50Ij48aW1nIGFsdD0iIiBzcmM9Ii9zaXRlcy9kZWZhdWx0L2ZpbGVzLzIwMjUtMDgvZGV0RmFjR3JheXNvbi5qcGciLz48L2Rpdj48L2Rpdj48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC10aXRsZSI+PHNwYW4gY2xhc3M9ImZpZWxkLWNvbnRlbnQiPkdyYXlzb24gQ291bnR5IERldGVudGlvbiBDZW50ZXI8L3NwYW4+PC9kaXY+PGRpdiBjbGFzcz0idmlld3MtZmllbGQgdmlld3MtZmllbGQtZmllbGQtZmllbGQtb2ZmaWNlLW5hbWUiPjxkaXYgY2xhc3M9ImZpZWxkLWNvbnRlbnQiPkNoaWNhZ28gRmllbGQgT2ZmaWNlPC9kaXY+PC9kaXY+PGRpdiBjbGFzcz0idmlld3MtZmllbGQgdmlld3MtZmllbGQtZmllbGQtZGV0ZW50aW9uLWZhY2lsaXR5LWxvY2F0aW8iPjxkaXYgY2xhc3M9ImZpZWxkLWNvbnRlbnQiPjxwIGNsYXNzPSJhZGRyZXNzIiB0cmFuc2xhdGU9Im5vIj48c3BhbiBjbGFzcz0iYWRkcmVzcy1saW5lMSI+MzIwIFNoYXcgU3RhdGlvbiBSb2FkPC9zcGFuPjxici8+CjxzcGFuIGNsYXNzPSJsb2NhbGl0eSI+TGVhY2hmaWVsZDwvc3Bhbj4sIDxzcGFuIGNsYXNzPSJhZG1pbmlzdHJhdGl2ZS1hcmVhIj5LWTwvc3Bhbj4gPHNwYW4gY2xhc3M9InBvc3RhbC1jb2RlIj40Mjc1NDwvc3Bhbj48YnIvPgo8c3BhbiBjbGFzcz0iY291bnRyeSI+VW5pdGVkIFN0YXRlczwvc3Bhbj48YnIvPjxzcGFuIGNsYXNzPSJjdC1hZGRyIj48L3NwYW4+PC9wPjwvZGl2PjwvZGl2PjxkaXYgY2xhc3M9InZpZXdzLWZpZWxkIHZpZXdzLWZpZWxkLXRpdGxlLTEiPjxzcGFuIGNsYXNzPSJmaWVsZC1jb250ZW50Ij48YSBocmVmPSIvZGV0YWluL2RldGVudGlvbi1mYWNpbGl0aWVzL2dyYXlzb24tY291bnR5LWRldGVudGlvbi1jZW50ZXIiIGhyZWZsYW5nPSJlbiI+R3JheXNvbiBDb3VudHkgRGV0ZW50aW9uIENlbnRlcjwvYT48L3NwYW4+PC9kaXY+PC9kaXY+CjwvbGk+",
            "source_urls": [
                "https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx",
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=3",
                "https://www.ice.gov/detain/detention-facilities/grayson-county-detention-center",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "3347 TAMIAMI TRAIL E,NAPLES,FL,34112": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "FL",
                "country": "",
                "locality": "NAPLES",
                "postal_code": 34112,
                "street": "3347 TAMIAMI TRAIL E",
            },
            "avg_stay_length": 2.80807522123894,
            "facility_type": "IGSA",
            "field_office": "",
            "image_url": "",
            "inspection_date": "2024-12-05",
            "name": "COLLIER COUNTY NAPLES JAIL CENTER",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 0.361370716510903, "non_criminal": 0.479750778816199},
                "male": {"allowed": True, "criminal": 8.0404984423675, "non_criminal": 7.01557632398745},
            },
            "raw_scrape": "",
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "3855 SOUTH JOHN YOUNG PARKWAY,ORLANDO,FL,32839": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "FL",
                "country": "",
                "locality": "ORLANDO",
                "postal_code": 32839,
                "street": "3855 SOUTH JOHN YOUNG PARKWAY",
            },
            "avg_stay_length": 2.23872180451128,
            "facility_type": "USMS IGA",
            "field_office": "",
            "image_url": "",
            "inspection_date": "2024-08-15",
            "name": "ORANGE COUNTY JAIL (FL)",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 0.582554517133956, "non_criminal": 1.87850467289719},
                "male": {"allowed": True, "criminal": 5.47663551401864, "non_criminal": 10.7476635514016},
            },
            "raw_scrape": "",
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "406 NORTH AVENUE D,SAN LUIS,AZ,85349": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "AZ",
                "country": "United States",
                "locality": "San Luis",
                "postal_code": "85349",
                "street": "406 North Avenue D",
            },
            "avg_stay_length": 16.0316045380875,
            "facility_type": "IGSA",
            "field_office": "San Diego Field Office",
            "image_url": "https://www.ice.gov/assets/pages/detention/facilities/sanLuisDetCntr.jpg",
            "inspection_date": "2024-09-26",
            "name": "SAN LUIS REGIONAL DETENTION CENTER",
            "page_updated_date": "2025-02-10 18:54:02+05:00",
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 2.28971962616822, "non_criminal": 40.0778816199377},
                "male": {"allowed": True, "criminal": 30.4766355140187, "non_criminal": 139.68847352025},
            },
            "raw_scrape": "PGxpIGNsYXNzPSJncmlkIj48ZGl2IGNsYXNzPSJncmlkX19jb250ZW50Ij48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1pbWFnZS1maWxlIj48ZGl2IGNsYXNzPSJmaWVsZC1jb250ZW50Ij48aW1nIGFsdD0iIiBzcmM9Ii9hc3NldHMvcGFnZXMvZGV0ZW50aW9uL2ZhY2lsaXRpZXMvc2FuTHVpc0RldENudHIuanBnIi8+PC9kaXY+PC9kaXY+PGRpdiBjbGFzcz0idmlld3MtZmllbGQgdmlld3MtZmllbGQtdGl0bGUiPjxzcGFuIGNsYXNzPSJmaWVsZC1jb250ZW50Ij5TYW4gTHVpcyBSZWdpb25hbCBEZXRlbnRpb24gQ2VudGVyPC9zcGFuPjwvZGl2PjxkaXYgY2xhc3M9InZpZXdzLWZpZWxkIHZpZXdzLWZpZWxkLWZpZWxkLWZpZWxkLW9mZmljZS1uYW1lIj48ZGl2IGNsYXNzPSJmaWVsZC1jb250ZW50Ij5TYW4gRGllZ28gRmllbGQgT2ZmaWNlPC9kaXY+PC9kaXY+PGRpdiBjbGFzcz0idmlld3MtZmllbGQgdmlld3MtZmllbGQtZmllbGQtZGV0ZW50aW9uLWZhY2lsaXR5LWxvY2F0aW8iPjxkaXYgY2xhc3M9ImZpZWxkLWNvbnRlbnQiPjxwIGNsYXNzPSJhZGRyZXNzIiB0cmFuc2xhdGU9Im5vIj48c3BhbiBjbGFzcz0iYWRkcmVzcy1saW5lMSI+NDA2IE5vcnRoIEF2ZW51ZSBEPC9zcGFuPjxici8+CjxzcGFuIGNsYXNzPSJsb2NhbGl0eSI+U2FuIEx1aXM8L3NwYW4+LCA8c3BhbiBjbGFzcz0iYWRtaW5pc3RyYXRpdmUtYXJlYSI+QVo8L3NwYW4+IDxzcGFuIGNsYXNzPSJwb3N0YWwtY29kZSI+ODUzNDk8L3NwYW4+PGJyLz4KPHNwYW4gY2xhc3M9ImNvdW50cnkiPlVuaXRlZCBTdGF0ZXM8L3NwYW4+PGJyLz48c3BhbiBjbGFzcz0iY3QtYWRkciI+PC9zcGFuPjwvcD48L2Rpdj48L2Rpdj48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC10aXRsZS0xIj48c3BhbiBjbGFzcz0iZmllbGQtY29udGVudCI+PGEgaHJlZj0iL2RldGFpbi9kZXRlbnRpb24tZmFjaWxpdGllcy9zYW4tbHVpcy1yZWdpb25hbC1kZXRlbnRpb24tY2VudGVyIiBocmVmbGFuZz0iZW4iPlNhbiBMdWlzIFJlZ2lvbmFsIERldGVudGlvbiBDZW50ZXI8L2E+PC9zcGFuPjwvZGl2PjwvZGl2Pgo8L2xpPg==",
            "source_urls": [
                "https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx",
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=5",
                "https://www.ice.gov/detain/detention-facilities/san-luis-regional-detention-center",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "409 FM 1144,KARNES CITY,TX,78118": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "TX",
                "country": "United States",
                "locality": "Karnes City",
                "postal_code": "78118",
                "street": "409 FM 1144",
            },
            "avg_stay_length": 32.4188289322618,
            "facility_type": "DIGSA",
            "field_office": "San Antonio Field Office",
            "image_url": "https://www.ice.gov/sites/default/files/images/detention/karnetx_0.jpg",
            "inspection_date": "2025-06-05",
            "name": "KARNES COUNTY IMMIGRATION PROCESSING CENTER",
            "page_updated_date": "2025-08-18 15:00:23+04:00",
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 18.8971962616822, "non_criminal": 254.841121495331},
                "male": {"allowed": True, "criminal": 54.8193146417444, "non_criminal": 617.056074766361},
            },
            "raw_scrape": "PGxpIGNsYXNzPSJncmlkIj48ZGl2IGNsYXNzPSJncmlkX19jb250ZW50Ij48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1pbWFnZS1maWxlIj48ZGl2IGNsYXNzPSJmaWVsZC1jb250ZW50Ij48aW1nIGFsdD0iIiBzcmM9Ii9zaXRlcy9kZWZhdWx0L2ZpbGVzL2ltYWdlcy9kZXRlbnRpb24va2FybmV0eF8wLmpwZyIvPjwvZGl2PjwvZGl2PjxkaXYgY2xhc3M9InZpZXdzLWZpZWxkIHZpZXdzLWZpZWxkLXRpdGxlIj48c3BhbiBjbGFzcz0iZmllbGQtY29udGVudCI+S2FybmVzIENvdW50eSBJbW1pZ3JhdGlvbiBQcm9jZXNzaW5nIENlbnRlcjwvc3Bhbj48L2Rpdj48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1maWVsZC1vZmZpY2UtbmFtZSI+PGRpdiBjbGFzcz0iZmllbGQtY29udGVudCI+U2FuIEFudG9uaW8gRmllbGQgT2ZmaWNlPC9kaXY+PC9kaXY+PGRpdiBjbGFzcz0idmlld3MtZmllbGQgdmlld3MtZmllbGQtZmllbGQtZGV0ZW50aW9uLWZhY2lsaXR5LWxvY2F0aW8iPjxkaXYgY2xhc3M9ImZpZWxkLWNvbnRlbnQiPjxwIGNsYXNzPSJhZGRyZXNzIiB0cmFuc2xhdGU9Im5vIj48c3BhbiBjbGFzcz0iYWRkcmVzcy1saW5lMSI+NDA5IEZNIDExNDQ8L3NwYW4+PGJyLz4KPHNwYW4gY2xhc3M9ImxvY2FsaXR5Ij5LYXJuZXMgQ2l0eTwvc3Bhbj4sIDxzcGFuIGNsYXNzPSJhZG1pbmlzdHJhdGl2ZS1hcmVhIj5UWDwvc3Bhbj4gPHNwYW4gY2xhc3M9InBvc3RhbC1jb2RlIj43ODExODwvc3Bhbj48YnIvPgo8c3BhbiBjbGFzcz0iY291bnRyeSI+VW5pdGVkIFN0YXRlczwvc3Bhbj48YnIvPjxzcGFuIGNsYXNzPSJjdC1hZGRyIj48L3NwYW4+PC9wPjwvZGl2PjwvZGl2PjxkaXYgY2xhc3M9InZpZXdzLWZpZWxkIHZpZXdzLWZpZWxkLXRpdGxlLTEiPjxzcGFuIGNsYXNzPSJmaWVsZC1jb250ZW50Ij48YSBocmVmPSIvZGV0YWluL2RldGVudGlvbi1mYWNpbGl0aWVzL2thcm5lcy1jb3VudHktaXBjIiBocmVmbGFuZz0iZW4iPkthcm5lcyBDb3VudHkgSW1taWdyYXRpb24gUHJvY2Vzc2luZyBDZW50ZXI8L2E+PC9zcGFuPjwvZGl2PjwvZGl2Pgo8L2xpPg==",
            "source_urls": [
                "https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx",
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=3",
                "https://www.ice.gov/detain/detention-facilities/karnes-county-ipc",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "451 DOREMUS AVENUE,NEWARK,NJ,07105": {
            "_repaired_record": True,
            "address": {
                "administrative_area": "NJ",
                "country": "United States",
                "locality": "Newark",
                "postal_code": "07105",
                "street": "451 Doremus Avenue",
            },
            "avg_stay_length": 17.4443907156673,
            "facility_type": "CDF",
            "field_office": "Newark Field Office",
            "image_url": "https://www.ice.gov/sites/default/files/2025-05/detFacDelaney.png",
            "inspection_date": None,
            "name": "DELANEY HALL DETENTION FACILITY",
            "page_updated_date": "2025-09-04 08:48:58+04:00",
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 1.5607476635514, "non_criminal": 14.1401869158878},
                "male": {"allowed": True, "criminal": 26.8255451713395, "non_criminal": 144.118380062306},
            },
            "raw_scrape": "PGxpIGNsYXNzPSJncmlkIj48ZGl2IGNsYXNzPSJncmlkX19jb250ZW50Ij48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1pbWFnZS1maWxlIj48ZGl2IGNsYXNzPSJmaWVsZC1jb250ZW50Ij48aW1nIGFsdD0iIiBzcmM9Ii9zaXRlcy9kZWZhdWx0L2ZpbGVzLzIwMjUtMDUvZGV0RmFjRGVsYW5leS5wbmciLz48L2Rpdj48L2Rpdj48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC10aXRsZSI+PHNwYW4gY2xhc3M9ImZpZWxkLWNvbnRlbnQiPkRlbGFuZXkgSGFsbCBEZXRlbnRpb24gRmFjaWxpdHk8L3NwYW4+PC9kaXY+PGRpdiBjbGFzcz0idmlld3MtZmllbGQgdmlld3MtZmllbGQtZmllbGQtZmllbGQtb2ZmaWNlLW5hbWUiPjxkaXYgY2xhc3M9ImZpZWxkLWNvbnRlbnQiPk5ld2FyayBGaWVsZCBPZmZpY2U8L2Rpdj48L2Rpdj48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1kZXRlbnRpb24tZmFjaWxpdHktbG9jYXRpbyI+PGRpdiBjbGFzcz0iZmllbGQtY29udGVudCI+PHAgY2xhc3M9ImFkZHJlc3MiIHRyYW5zbGF0ZT0ibm8iPjxzcGFuIGNsYXNzPSJhZGRyZXNzLWxpbmUxIj40NTEgRG9yZW11cyBBdmVudWU8L3NwYW4+PGJyLz4KPHNwYW4gY2xhc3M9ImxvY2FsaXR5Ij5OZXdhcms8L3NwYW4+LCA8c3BhbiBjbGFzcz0iYWRtaW5pc3RyYXRpdmUtYXJlYSI+Tko8L3NwYW4+IDxzcGFuIGNsYXNzPSJwb3N0YWwtY29kZSI+MDcxMDU8L3NwYW4+PGJyLz4KPHNwYW4gY2xhc3M9ImNvdW50cnkiPlVuaXRlZCBTdGF0ZXM8L3NwYW4+PGJyLz48c3BhbiBjbGFzcz0iY3QtYWRkciI+PC9zcGFuPjwvcD48L2Rpdj48L2Rpdj48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC10aXRsZS0xIj48c3BhbiBjbGFzcz0iZmllbGQtY29udGVudCI+PGEgaHJlZj0iL2RldGFpbi9kZXRlbnRpb24tZmFjaWxpdGllcy9kZWxhbmV5LWhhbGwtZGV0ZW50aW9uLWZhY2lsaXR5IiBocmVmbGFuZz0iZW4iPkRlbGFuZXkgSGFsbCBEZXRlbnRpb24gRmFjaWxpdHk8L2E+PC9zcGFuPjwvZGl2PjwvZGl2Pgo8L2xpPg==",
            "source_urls": [
                "https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx",
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=1",
                "https://www.ice.gov/detain/detention-facilities/delaney-hall-detention-facility",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "5001 MALONEYVILLE RD,KNOXVILLE,TN,37918": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "TN",
                "country": "",
                "locality": "KNOXVILLE",
                "postal_code": 37918,
                "street": "5001 MALONEYVILLE RD",
            },
            "avg_stay_length": 3.50472914875322,
            "facility_type": "USMS IGA",
            "field_office": "",
            "image_url": "",
            "inspection_date": "2024-09-26",
            "name": "KNOX COUNTY DETENTION FACILITY",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 0.682242990654206, "non_criminal": 1.27725856697819},
                "male": {"allowed": True, "criminal": 12.6915887850465, "non_criminal": 11.9968847352023},
            },
            "raw_scrape": "",
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "555 GEO DRIVE,PHILIPSBURG,PA,16866": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "PA",
                "country": "United States",
                "locality": "Philipsburg",
                "postal_code": "16866",
                "street": "555 GEO Drive",
            },
            "avg_stay_length": 60.3703295188198,
            "facility_type": "DIGSA",
            "field_office": "Philadelphia Field Office",
            "image_url": "https://www.ice.gov/assets/pages/detention/facilities/moshannon.png",
            "inspection_date": "2025-03-06",
            "name": "MOSHANNON VALLEY PROCESSING CENTER",
            "page_updated_date": "2025-08-14 07:24:42+04:00",
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 25.7071651090343, "non_criminal": 22.4735202492212},
                "male": {"allowed": True, "criminal": 699.031152647976, "non_criminal": 637.196261682248},
            },
            "raw_scrape": "PGxpIGNsYXNzPSJncmlkIj48ZGl2IGNsYXNzPSJncmlkX19jb250ZW50Ij48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1pbWFnZS1maWxlIj48ZGl2IGNsYXNzPSJmaWVsZC1jb250ZW50Ij48aW1nIGFsdD0iIiBzcmM9Ii9hc3NldHMvcGFnZXMvZGV0ZW50aW9uL2ZhY2lsaXRpZXMvbW9zaGFubm9uLnBuZyIvPjwvZGl2PjwvZGl2PjxkaXYgY2xhc3M9InZpZXdzLWZpZWxkIHZpZXdzLWZpZWxkLXRpdGxlIj48c3BhbiBjbGFzcz0iZmllbGQtY29udGVudCI+TW9zaGFubm9uIFZhbGxleSBQcm9jZXNzaW5nIENlbnRlcjwvc3Bhbj48L2Rpdj48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1maWVsZC1vZmZpY2UtbmFtZSI+PGRpdiBjbGFzcz0iZmllbGQtY29udGVudCI+UGhpbGFkZWxwaGlhIEZpZWxkIE9mZmljZTwvZGl2PjwvZGl2PjxkaXYgY2xhc3M9InZpZXdzLWZpZWxkIHZpZXdzLWZpZWxkLWZpZWxkLWRldGVudGlvbi1mYWNpbGl0eS1sb2NhdGlvIj48ZGl2IGNsYXNzPSJmaWVsZC1jb250ZW50Ij48cCBjbGFzcz0iYWRkcmVzcyIgdHJhbnNsYXRlPSJubyI+PHNwYW4gY2xhc3M9ImFkZHJlc3MtbGluZTEiPjU1NSBHRU8gRHJpdmU8L3NwYW4+PGJyLz4KPHNwYW4gY2xhc3M9ImxvY2FsaXR5Ij5QaGlsaXBzYnVyZzwvc3Bhbj4sIDxzcGFuIGNsYXNzPSJhZG1pbmlzdHJhdGl2ZS1hcmVhIj5QQTwvc3Bhbj4gPHNwYW4gY2xhc3M9InBvc3RhbC1jb2RlIj4xNjg2Njwvc3Bhbj48YnIvPgo8c3BhbiBjbGFzcz0iY291bnRyeSI+VW5pdGVkIFN0YXRlczwvc3Bhbj48YnIvPjxzcGFuIGNsYXNzPSJjdC1hZGRyIj48L3NwYW4+PC9wPjwvZGl2PjwvZGl2PjxkaXYgY2xhc3M9InZpZXdzLWZpZWxkIHZpZXdzLWZpZWxkLXRpdGxlLTEiPjxzcGFuIGNsYXNzPSJmaWVsZC1jb250ZW50Ij48YSBocmVmPSIvZGV0YWluL2RldGVudGlvbi1mYWNpbGl0aWVzL21vc2hhbm5vbi12YWxsZXktcHJvY2Vzc2luZy1jZW50ZXIiIGhyZWZsYW5nPSJlbiI+TW9zaGFubm9uIFZhbGxleSBQcm9jZXNzaW5nIENlbnRlcjwvYT48L3NwYW4+PC9kaXY+PC9kaXY+CjwvbGk+",
            "source_urls": [
                "https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx",
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=4",
                "https://www.ice.gov/detain/detention-facilities/moshannon-valley-processing-center",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "651 FEDERAL DRIVE SUITE 104,GUAYNABO,PR,965": {
            "_repaired_record": True,
            "address": {
                "administrative_area": "PR",
                "country": "",
                "locality": "GUAYNABO",
                "postal_code": 965,
                "street": "651 FEDERAL DRIVE, SUITE 104",
            },
            "avg_stay_length": 4.94200351493849,
            "facility_type": "STAGING",
            "field_office": "",
            "image_url": "",
            "inspection_date": None,
            "name": "SAN JUAN STAGING",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 0.196261682242991, "non_criminal": 1.01869158878505},
                "male": {"allowed": True, "criminal": 3.46105919003115, "non_criminal": 8.28037383177564},
            },
            "raw_scrape": "",
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "6920 DIGITAL RD,EL PASO,TX,79936": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "TX",
                "country": "",
                "locality": "EL PASO",
                "postal_code": 79936,
                "street": "6920 DIGITAL RD",
            },
            "avg_stay_length": 2.1,
            "facility_type": "CDF",
            "field_office": "",
            "image_url": "",
            "inspection_date": None,
            "name": "ERO EL PASO CAMP EAST MONTANA",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 0.0124610591900312, "non_criminal": 0.0186915887850467},
                "male": {"allowed": True, "criminal": 2.09345794392522, "non_criminal": 4.56074766355134},
            },
            "raw_scrape": "",
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "705 HANOVER STREET,HAMILTON,OH,45011": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "OH",
                "country": "United States",
                "locality": "Hamilton",
                "postal_code": "45011",
                "street": "705 Hanover Street",
            },
            "avg_stay_length": 27.7724268177526,
            "facility_type": "USMS IGA",
            "field_office": "Detroit Field Office",
            "image_url": "https://www.ice.gov/sites/default/files/images/detFacButler.png",
            "inspection_date": None,
            "name": "BUTLER COUNTY JAIL",
            "page_updated_date": "2025-05-15 07:19:46+04:00",
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 1.80685358255452, "non_criminal": 12.0155763239875},
                "male": {"allowed": True, "criminal": 33.5358255451713, "non_criminal": 94.968847352025},
            },
            "raw_scrape": "PGxpIGNsYXNzPSJncmlkIj48ZGl2IGNsYXNzPSJncmlkX19jb250ZW50Ij48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1pbWFnZS1maWxlIj48ZGl2IGNsYXNzPSJmaWVsZC1jb250ZW50Ij48aW1nIGFsdD0iIiBzcmM9Ii9zaXRlcy9kZWZhdWx0L2ZpbGVzL2ltYWdlcy9kZXRGYWNCdXRsZXIucG5nIi8+PC9kaXY+PC9kaXY+PGRpdiBjbGFzcz0idmlld3MtZmllbGQgdmlld3MtZmllbGQtdGl0bGUiPjxzcGFuIGNsYXNzPSJmaWVsZC1jb250ZW50Ij5CdXRsZXIgQ291bnR5IFNoZXJpZmbigJlzIE9mZmljZTwvc3Bhbj48L2Rpdj48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1maWVsZC1vZmZpY2UtbmFtZSI+PGRpdiBjbGFzcz0iZmllbGQtY29udGVudCI+RGV0cm9pdCBGaWVsZCBPZmZpY2U8L2Rpdj48L2Rpdj48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1kZXRlbnRpb24tZmFjaWxpdHktbG9jYXRpbyI+PGRpdiBjbGFzcz0iZmllbGQtY29udGVudCI+PHAgY2xhc3M9ImFkZHJlc3MiIHRyYW5zbGF0ZT0ibm8iPjxzcGFuIGNsYXNzPSJhZGRyZXNzLWxpbmUxIj43MDUgSGFub3ZlciBTdHJlZXQ8L3NwYW4+PGJyLz4KPHNwYW4gY2xhc3M9ImxvY2FsaXR5Ij5IYW1pbHRvbjwvc3Bhbj4sIDxzcGFuIGNsYXNzPSJhZG1pbmlzdHJhdGl2ZS1hcmVhIj5PSDwvc3Bhbj4gPHNwYW4gY2xhc3M9InBvc3RhbC1jb2RlIj40NTAxMTwvc3Bhbj48YnIvPgo8c3BhbiBjbGFzcz0iY291bnRyeSI+VW5pdGVkIFN0YXRlczwvc3Bhbj48YnIvPjxzcGFuIGNsYXNzPSJjdC1hZGRyIj48L3NwYW4+PC9wPjwvZGl2PjwvZGl2PjxkaXYgY2xhc3M9InZpZXdzLWZpZWxkIHZpZXdzLWZpZWxkLXRpdGxlLTEiPjxzcGFuIGNsYXNzPSJmaWVsZC1jb250ZW50Ij48YSBocmVmPSIvZGV0YWluL2RldGVudGlvbi1mYWNpbGl0aWVzL2J1dGxlci1jb3VudHktc2hlcmlmZnMtb2ZmaWNlIiBocmVmbGFuZz0iZW4iPkJ1dGxlciBDb3VudHkgU2hlcmlmZuKAmXMgT2ZmaWNlPC9hPjwvc3Bhbj48L2Rpdj48L2Rpdj4KPC9saT4=",
            "source_urls": [
                "https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx",
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=0",
                "https://www.ice.gov/detain/detention-facilities/butler-county-sheriffs-office",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "715 5TH AVENUE,HOLDREGE,NE,68949": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "NE",
                "country": "United States",
                "locality": "Holdrege",
                "postal_code": "68949",
                "street": "715 5th Avenue",
            },
            "avg_stay_length": 38.6484375,
            "facility_type": "USMS IGA",
            "field_office": "St. Paul Field Office",
            "image_url": "https://www.ice.gov/assets/pages/detention/facilities/phelpsCoJail.jpg",
            "inspection_date": "2025-02-06",
            "name": "PHELPS COUNTY JAIL (NE)",
            "page_updated_date": "2025-02-10 18:50:51+05:00",
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 1.19626168224299, "non_criminal": 0.355140186915888},
                "male": {"allowed": True, "criminal": 23.607476635514, "non_criminal": 5.74454828660436},
            },
            "raw_scrape": "PGxpIGNsYXNzPSJncmlkIj48ZGl2IGNsYXNzPSJncmlkX19jb250ZW50Ij48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1pbWFnZS1maWxlIj48ZGl2IGNsYXNzPSJmaWVsZC1jb250ZW50Ij48aW1nIGFsdD0iIiBzcmM9Ii9hc3NldHMvcGFnZXMvZGV0ZW50aW9uL2ZhY2lsaXRpZXMvcGhlbHBzQ29KYWlsLmpwZyIvPjwvZGl2PjwvZGl2PjxkaXYgY2xhc3M9InZpZXdzLWZpZWxkIHZpZXdzLWZpZWxkLXRpdGxlIj48c3BhbiBjbGFzcz0iZmllbGQtY29udGVudCI+UGhlbHBzIENvdW50eSBKYWlsPC9zcGFuPjwvZGl2PjxkaXYgY2xhc3M9InZpZXdzLWZpZWxkIHZpZXdzLWZpZWxkLWZpZWxkLWZpZWxkLW9mZmljZS1uYW1lIj48ZGl2IGNsYXNzPSJmaWVsZC1jb250ZW50Ij5TdC4gUGF1bCBGaWVsZCBPZmZpY2U8L2Rpdj48L2Rpdj48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1kZXRlbnRpb24tZmFjaWxpdHktbG9jYXRpbyI+PGRpdiBjbGFzcz0iZmllbGQtY29udGVudCI+PHAgY2xhc3M9ImFkZHJlc3MiIHRyYW5zbGF0ZT0ibm8iPjxzcGFuIGNsYXNzPSJhZGRyZXNzLWxpbmUxIj43MTUgNXRoIEF2ZW51ZTwvc3Bhbj48YnIvPgo8c3BhbiBjbGFzcz0ibG9jYWxpdHkiPkhvbGRyZWdlPC9zcGFuPiwgPHNwYW4gY2xhc3M9ImFkbWluaXN0cmF0aXZlLWFyZWEiPk5FPC9zcGFuPiA8c3BhbiBjbGFzcz0icG9zdGFsLWNvZGUiPjY4OTQ5PC9zcGFuPjxici8+CjxzcGFuIGNsYXNzPSJjb3VudHJ5Ij5Vbml0ZWQgU3RhdGVzPC9zcGFuPjxici8+PHNwYW4gY2xhc3M9ImN0LWFkZHIiPjwvc3Bhbj48L3A+PC9kaXY+PC9kaXY+PGRpdiBjbGFzcz0idmlld3MtZmllbGQgdmlld3MtZmllbGQtdGl0bGUtMSI+PHNwYW4gY2xhc3M9ImZpZWxkLWNvbnRlbnQiPjxhIGhyZWY9Ii9kZXRhaW4vZGV0ZW50aW9uLWZhY2lsaXRpZXMvcGhlbHBzLWNvdW50eS1qYWlsIiBocmVmbGFuZz0iZW4iPlBoZWxwcyBDb3VudHkgSmFpbDwvYT48L3NwYW4+PC9kaXY+PC9kaXY+CjwvbGk+",
            "source_urls": [
                "https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx",
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=4",
                "https://www.ice.gov/detain/detention-facilities/phelps-county-jail",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "CoreCivic Laredo Processing Center": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "TX",
                "country": "United States",
                "locality": "Laredo",
                "postal_code": "78401",
                "street": "4702 East Saunders",
            },
            "avg_stay_length": 0,
            "facility_type": "",
            "field_office": "Harlingen Field Office",
            "image_url": "https://www.ice.gov/sites/default/files/images/detention/lrdicdf.jpg",
            "inspection_date": None,
            "name": "CoreCivic Laredo Processing Center",
            "page_updated_date": "2025-02-10 15:38:10+05:00",
            "phone": "",
            "population": {
                "female": {"allowed": False, "criminal": 0, "non_criminal": 0},
                "male": {"allowed": False, "criminal": 0, "non_criminal": 0},
            },
            "raw_scrape": "PGxpIGNsYXNzPSJncmlkIj48ZGl2IGNsYXNzPSJncmlkX19jb250ZW50Ij48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1pbWFnZS1maWxlIj48ZGl2IGNsYXNzPSJmaWVsZC1jb250ZW50Ij48aW1nIGFsdD0iIiBzcmM9Ii9zaXRlcy9kZWZhdWx0L2ZpbGVzL2ltYWdlcy9kZXRlbnRpb24vbHJkaWNkZi5qcGciLz48L2Rpdj48L2Rpdj48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC10aXRsZSI+PHNwYW4gY2xhc3M9ImZpZWxkLWNvbnRlbnQiPkNvcmVDaXZpYyBMYXJlZG8gUHJvY2Vzc2luZyBDZW50ZXI8L3NwYW4+PC9kaXY+PGRpdiBjbGFzcz0idmlld3MtZmllbGQgdmlld3MtZmllbGQtZmllbGQtZmllbGQtb2ZmaWNlLW5hbWUiPjxkaXYgY2xhc3M9ImZpZWxkLWNvbnRlbnQiPkhhcmxpbmdlbiBGaWVsZCBPZmZpY2U8L2Rpdj48L2Rpdj48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1kZXRlbnRpb24tZmFjaWxpdHktbG9jYXRpbyI+PGRpdiBjbGFzcz0iZmllbGQtY29udGVudCI+PHAgY2xhc3M9ImFkZHJlc3MiIHRyYW5zbGF0ZT0ibm8iPjxzcGFuIGNsYXNzPSJhZGRyZXNzLWxpbmUxIj40NzAyIEVhc3QgU2F1bmRlcnM8L3NwYW4+PGJyLz4KPHNwYW4gY2xhc3M9ImxvY2FsaXR5Ij5MYXJlZG88L3NwYW4+LCA8c3BhbiBjbGFzcz0iYWRtaW5pc3RyYXRpdmUtYXJlYSI+VFg8L3NwYW4+IDxzcGFuIGNsYXNzPSJwb3N0YWwtY29kZSI+Nzg0MDE8L3NwYW4+PGJyLz4KPHNwYW4gY2xhc3M9ImNvdW50cnkiPlVuaXRlZCBTdGF0ZXM8L3NwYW4+PGJyLz48c3BhbiBjbGFzcz0iY3QtYWRkciI+PC9zcGFuPjwvcD48L2Rpdj48L2Rpdj48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC10aXRsZS0xIj48c3BhbiBjbGFzcz0iZmllbGQtY29udGVudCI+PGEgaHJlZj0iL2RldGFpbi9kZXRlbnRpb24tZmFjaWxpdGllcy9sYXJlZG8tZGV0ZW50aW9uLWNlbnRlciIgaHJlZmxhbmc9ImVuIj5Db3JlQ2l2aWMgTGFyZWRvIFByb2Nlc3NpbmcgQ2VudGVyPC9hPjwvc3Bhbj48L2Rpdj48L2Rpdj4KPC9saT4=",
            "source_urls": [
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=1",
                "https://www.ice.gov/detain/detention-facilities/laredo-detention-center",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "DoD Detention Facility at Fort Bliss": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "TX",
                "country": "United States",
                "locality": "El Paso",
                "postal_code": "79936",
                "street": "11541 Montana Avenue",
            },
            "avg_stay_length": 0,
            "facility_type": "",
            "field_office": "El Paso Field Office",
            "image_url": "https://www.ice.gov/sites/default/files/2025-09/detFacFortBliss.jpg",
            "inspection_date": None,
            "name": "DoD Detention Facility at Fort Bliss",
            "page_updated_date": "2025-09-02 14:01:55+04:00",
            "phone": "",
            "population": {
                "female": {"allowed": False, "criminal": 0, "non_criminal": 0},
                "male": {"allowed": False, "criminal": 0, "non_criminal": 0},
            },
            "raw_scrape": "PGxpIGNsYXNzPSJncmlkIj48ZGl2IGNsYXNzPSJncmlkX19jb250ZW50Ij48ZGl2IGNsYXNzPSJ2aWV3cy1maWVsZCB2aWV3cy1maWVsZC1maWVsZC1pbWFnZS1maWxlIj48ZGl2IGNsYXNzPSJmaWVsZC1jb250ZW50Ij48aW1nIGFsdD0iIiBzcmM9Ii9zaXRlcy9kZWZhdWx0L2ZpbGVzLzIwMjUtMDkvZGV0RmFjRm9ydEJsaXNzLmpwZyIvPjwvZGl2PjwvZGl2PjxkaXYgY2xhc3M9InZpZXdzLWZpZWxkIHZpZXdzLWZpZWxkLXRpdGxlIj48c3BhbiBjbGFzcz0iZmllbGQtY29udGVudCI+RG9EIERldGVudGlvbiBGYWNpbGl0eSBhdCBGb3J0IEJsaXNzPC9zcGFuPjwvZGl2PjxkaXYgY2xhc3M9InZpZXdzLWZpZWxkIHZpZXdzLWZpZWxkLWZpZWxkLWZpZWxkLW9mZmljZS1uYW1lIj48ZGl2IGNsYXNzPSJmaWVsZC1jb250ZW50Ij5FbCBQYXNvIEZpZWxkIE9mZmljZTwvZGl2PjwvZGl2PjxkaXYgY2xhc3M9InZpZXdzLWZpZWxkIHZpZXdzLWZpZWxkLWZpZWxkLWRldGVudGlvbi1mYWNpbGl0eS1sb2NhdGlvIj48ZGl2IGNsYXNzPSJmaWVsZC1jb250ZW50Ij48cCBjbGFzcz0iYWRkcmVzcyIgdHJhbnNsYXRlPSJubyI+PHNwYW4gY2xhc3M9ImFkZHJlc3MtbGluZTEiPjExNTQxIE1vbnRhbmEgQXZlbnVlPC9zcGFuPjxici8+CjxzcGFuIGNsYXNzPSJhZGRyZXNzLWxpbmUyIj5TdWl0ZSBFPC9zcGFuPjxici8+CjxzcGFuIGNsYXNzPSJsb2NhbGl0eSI+RWwgUGFzbzwvc3Bhbj4sIDxzcGFuIGNsYXNzPSJhZG1pbmlzdHJhdGl2ZS1hcmVhIj5UWDwvc3Bhbj4gPHNwYW4gY2xhc3M9InBvc3RhbC1jb2RlIj43OTkzNjwvc3Bhbj48YnIvPgo8c3BhbiBjbGFzcz0iY291bnRyeSI+VW5pdGVkIFN0YXRlczwvc3Bhbj48YnIvPjxzcGFuIGNsYXNzPSJjdC1hZGRyIj48L3NwYW4+PC9wPjwvZGl2PjwvZGl2PjxkaXYgY2xhc3M9InZpZXdzLWZpZWxkIHZpZXdzLWZpZWxkLXRpdGxlLTEiPjxzcGFuIGNsYXNzPSJmaWVsZC1jb250ZW50Ij48YSBocmVmPSIvZGV0YWluL2RldGVudGlvbi1mYWNpbGl0aWVzL2RvZC1kZXRlbnRpb24tZmFjaWxpdHktZm9ydC1ibGlzcyIgaHJlZmxhbmc9ImVuIj5Eb0QgRGV0ZW50aW9uIEZhY2lsaXR5IGF0IEZvcnQgQmxpc3M8L2E+PC9zcGFuPjwvZGl2PjwvZGl2Pgo8L2xpPg==",
            "source_urls": [
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=1",
                "https://www.ice.gov/detain/detention-facilities/dod-detention-facility-fort-bliss",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "PARK STREET,FONDA,NY,12068": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "NY",
                "country": "",
                "locality": "FONDA",
                "postal_code": 12068,
                "street": "PARK STREET",
            },
            "avg_stay_length": 1.95475113122172,
            "facility_type": "IGSA",
            "field_office": "",
            "image_url": "",
            "inspection_date": None,
            "name": "MONTGOMERY COUNTY JAIL",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 0.0, "non_criminal": 0.0685358255451713},
                "male": {"allowed": True, "criminal": 0.286604361370716, "non_criminal": 1.06853582554517},
            },
            "raw_scrape": "",
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
    },
    "scrape_runtime": 48.883458614349365,
    "scraped_date": "2025-09-08 00:00:17.837345",
}
