# load_existing_data function and static facility data


facilities_data = {
    "enrich_runtime": 0,
    "facilities": {
        "12501 GATEWAY BLVD S,EL PASO,TX,79934": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "TX",
                "country": "",
                "locality": "EL PASO",
                "postal_code": 79934,
                "street": "12501 GATEWAY BLVD S",
            },
            "avg_stay_length": 4.6051766051766,
            "facility_type": "STAGING",
            "field_office": {
                "address": {
                    "administrative_area": "TX",
                    "country": "United States",
                    "locality": "El Paso",
                    "postal_code": "79936",
                    "street": "11541 Montana Ave Suite E",
                },
                "address_str": "11541 Montana Ave Suite E El Paso, TX 79936",
                "aor": "West Texas, New Mexico",
                "email": "ElPaso.Outreach@ice.dhs.gov",
                "field_office": "El Paso Field Office",
                "name": "El Paso - ERO",
                "phone": "(915) 225-1901",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=2&exposed_form_display=1"],
            },
            "image_url": "",
            "inspection_date": None,
            "name": "EL PASO SOFT SIDED FACILITY",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 3.58255451713394, "non_criminal": 12.3364485981307},
                "male": {"allowed": True, "criminal": 57.4423676012446, "non_criminal": 134.909657320886},
            },
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "1300 LANGE CT,BARABOO,WI,53913": {
            "_repaired_record": True,
            "address": {
                "administrative_area": "WI",
                "country": "",
                "locality": "BARABOO",
                "postal_code": 53913,
                "street": "1300 LANGE CT.",
            },
            "avg_stay_length": 6.875,
            "facility_type": "USMS IGA",
            "field_office": {
                "address": {
                    "administrative_area": "IL",
                    "country": "United States",
                    "locality": "Chicago",
                    "postal_code": "60605",
                    "street": "101 W Ida B Wells Drive Suite 4000",
                },
                "address_str": "101 W Ida B Wells Drive Suite 4000 Chicago, IL 60605",
                "aor": "Illinois, Indiana, Wisconsin, Missouri, Kentucky, Kansas",
                "email": "Chicago.Outreach@ice.dhs.gov",
                "field_office": "Chicago Field Office",
                "name": "Chicago - ERO",
                "phone": "(872) 351-3990",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=1&exposed_form_display=1"],
            },
            "image_url": "",
            "inspection_date": None,
            "name": "SAUK COUNTY SHERIFF",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 0.0, "non_criminal": 0.00623052959501558},
                "male": {"allowed": True, "criminal": 0.59190031152648, "non_criminal": 1.07165109034268},
            },
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "1623 E J STREET,TACOMA,WA,98421": {
            "_repaired_record": True,
            "address": {
                "administrative_area": "WA",
                "country": "United States",
                "locality": "Tacoma",
                "postal_code": "98421-1615",
                "street": "1623 E J Street, Suite 2",
            },
            "avg_stay_length": 68.9292759201347,
            "facility_type": "CDF",
            "field_office": {
                "address": {
                    "administrative_area": "WA",
                    "country": "United States",
                    "locality": "Seattle",
                    "postal_code": "98168",
                    "street": "12500 Tukwila International Boulevard",
                },
                "address_str": "12500 Tukwila International Boulevard Seattle, WA 98168",
                "aor": "Alaska, Oregon, Washington",
                "email": "Seattle.Outreach@ice.dhs.gov",
                "field_office": "Seattle Field Office",
                "name": "Seattle - ERO",
                "phone": "(206) 277-2000",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=7&exposed_form_display=1"],
            },
            "image_url": "https://www.ice.gov/sites/default/files/images/nwIPC.png",
            "inspection_date": "2025-01-30",
            "name": "NORTHWEST ICE PROCESSSING CENTER",
            "page_updated_date": "2025-08-20 07:47:00+04:00",
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 45.6323987538941, "non_criminal": 78.5451713395638},
                "male": {"allowed": True, "criminal": 403.180685358257, "non_criminal": 627.056074766356},
            },
            "source_urls": [
                "https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx",
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=4",
                "https://www.ice.gov/detain/detention-facilities/northwest-ice-processing-center-nwipc",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "216 S BROAD ST,GUTHRIE,OK,73044": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "OK",
                "country": "",
                "locality": "GUTHRIE",
                "postal_code": 73044,
                "street": "216 S BROAD ST",
            },
            "avg_stay_length": 2.69458128078818,
            "facility_type": "USMS IGA",
            "field_office": {
                "address": {
                    "administrative_area": "TX",
                    "country": "United States",
                    "locality": "Dallas",
                    "postal_code": "75247",
                    "street": "8101 N. Stemmons Frwy",
                },
                "address_str": "8101 N. Stemmons Frwy Dallas, TX 75247",
                "aor": "North Texas, Oklahoma",
                "email": "Dallas.Outreach@ice.dhs.gov",
                "field_office": "Dallas Field Office",
                "name": "Dallas - ERO",
                "phone": "(972) 367-2200",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=1&exposed_form_display=1"],
            },
            "image_url": "",
            "inspection_date": "2025-05-13",
            "name": "LOGAN COUNTY JAIL",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": False, "criminal": 0.0467289719626168, "non_criminal": 0.158878504672897},
                "male": {"allowed": False, "criminal": 0.551401869158878, "non_criminal": 1.16510903426791},
            },
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "219 EAST FREMONT AVENUE,RIGBY,ID,83442": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "ID",
                "country": "",
                "locality": "RIGBY",
                "postal_code": 83442,
                "street": "219 EAST FREMONT AVENUE",
            },
            "avg_stay_length": 2.86121673003802,
            "facility_type": "IGSA",
            "field_office": {
                "address": {
                    "administrative_area": "UT",
                    "country": "United States",
                    "locality": "West Valley City",
                    "postal_code": "84119-6096",
                    "street": "2975 Decker Lake Drive Suite 100",
                },
                "address_str": "2975 Decker Lake Drive Suite 100 West Valley City, UT 84119-6096",
                "aor": "Utah, Idaho, Montana, Nevada",
                "email": "SaltLakeCity.Outreach@ice.dhs.gov",
                "field_office": "Salt Lake City Field Office",
                "name": "West Valley City - ERO",
                "phone": "(801) 736-1200",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=7&exposed_form_display=1"],
            },
            "image_url": "",
            "inspection_date": "2024-07-18",
            "name": "JEFFERSON COUNTY JAIL",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 0.0311526479750779, "non_criminal": 0.0249221183800623},
                "male": {"allowed": True, "criminal": 3.56386292834889, "non_criminal": 1.22118380062305},
            },
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "320 SHAW STATION ROAD,LEITCHFIELD,KY,42754": {
            "_repaired_record": True,
            "address": {
                "administrative_area": "KY",
                "country": "United States",
                "locality": "Leachfield",
                "postal_code": "42754",
                "street": "320 Shaw Station Road",
            },
            "avg_stay_length": 16.1679626749611,
            "facility_type": "USMS IGA",
            "field_office": {
                "address": {
                    "administrative_area": "IL",
                    "country": "United States",
                    "locality": "Chicago",
                    "postal_code": "60605",
                    "street": "101 W Ida B Wells Drive Suite 4000",
                },
                "address_str": "101 W Ida B Wells Drive Suite 4000 Chicago, IL 60605",
                "aor": "Illinois, Indiana, Wisconsin, Missouri, Kentucky, Kansas",
                "email": "Chicago.Outreach@ice.dhs.gov",
                "field_office": "Chicago Field Office",
                "name": "Chicago - ERO",
                "phone": "(872) 351-3990",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=1&exposed_form_display=1"],
            },
            "image_url": "https://www.ice.gov/sites/default/files/2025-08/detFacGrayson.jpg",
            "inspection_date": "2025-08-21",
            "name": "GRAYSON COUNTY JAIL",
            "page_updated_date": "2025-08-20 08:07:50+04:00",
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 19.7383177570094, "non_criminal": 36.9844236760124},
                "male": {"allowed": True, "criminal": 5.07165109034266, "non_criminal": 2.83800623052959},
            },
            "source_urls": [
                "https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx",
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=3",
                "https://www.ice.gov/detain/detention-facilities/grayson-county-detention-center",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "3347 TAMIAMI TRAIL E,NAPLES,FL,34112": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "FL",
                "country": "",
                "locality": "NAPLES",
                "postal_code": 34112,
                "street": "3347 TAMIAMI TRAIL E",
            },
            "avg_stay_length": 2.80807522123894,
            "facility_type": "IGSA",
            "field_office": {
                "address": {
                    "administrative_area": "FL",
                    "country": "United States",
                    "locality": "Plantation",
                    "postal_code": "33324",
                    "street": "865 SW 78th Avenue Suite 101",
                },
                "address_str": "865 SW 78th Avenue Suite 101 Plantation, FL 33324",
                "aor": "Florida, Puerto Rico, U.S. Virgin Islands",
                "email": "Miami.Outreach@ice.dhs.gov",
                "field_office": "Miami Field Office",
                "name": "Plantation - ERO",
                "phone": "(954) 236-4900",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=5&exposed_form_display=1"],
            },
            "image_url": "",
            "inspection_date": "2024-12-05",
            "name": "COLLIER COUNTY NAPLES JAIL CENTER",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 0.361370716510903, "non_criminal": 0.479750778816199},
                "male": {"allowed": True, "criminal": 8.0404984423675, "non_criminal": 7.01557632398745},
            },
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "3855 SOUTH JOHN YOUNG PARKWAY,ORLANDO,FL,32839": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "FL",
                "country": "",
                "locality": "ORLANDO",
                "postal_code": 32839,
                "street": "3855 SOUTH JOHN YOUNG PARKWAY",
            },
            "avg_stay_length": 2.23872180451128,
            "facility_type": "USMS IGA",
            "field_office": {
                "address": {
                    "administrative_area": "FL",
                    "country": "United States",
                    "locality": "Plantation",
                    "postal_code": "33324",
                    "street": "865 SW 78th Avenue Suite 101",
                },
                "address_str": "865 SW 78th Avenue Suite 101 Plantation, FL 33324",
                "aor": "Florida, Puerto Rico, U.S. Virgin Islands",
                "email": "Miami.Outreach@ice.dhs.gov",
                "field_office": "Miami Field Office",
                "name": "Plantation - ERO",
                "phone": "(954) 236-4900",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=5&exposed_form_display=1"],
            },
            "image_url": "",
            "inspection_date": "2024-08-15",
            "name": "ORANGE COUNTY JAIL (FL)",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 0.582554517133956, "non_criminal": 1.87850467289719},
                "male": {"allowed": True, "criminal": 5.47663551401864, "non_criminal": 10.7476635514016},
            },
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "406 NORTH AVENUE D,SAN LUIS,AZ,85349": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "AZ",
                "country": "United States",
                "locality": "San Luis",
                "postal_code": "85349",
                "street": "406 North Avenue D",
            },
            "avg_stay_length": 16.0316045380875,
            "facility_type": "IGSA",
            "field_office": {
                "address": {
                    "administrative_area": "CA",
                    "country": "United States",
                    "locality": "San Diego",
                    "postal_code": "92101",
                    "street": "880 Front Street #2242",
                },
                "address_str": "880 Front Street #2242 San Diego, CA 92101",
                "aor": "San Diego and Imperial County",
                "email": "SanDiego.Outreach@ice.dhs.gov",
                "field_office": "San Diego Field Office",
                "name": "San Diego - ERO",
                "phone": "(619) 436-0410",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=6&exposed_form_display=1"],
            },
            "image_url": "https://www.ice.gov/assets/pages/detention/facilities/sanLuisDetCntr.jpg",
            "inspection_date": "2024-09-26",
            "name": "SAN LUIS REGIONAL DETENTION CENTER",
            "page_updated_date": "2025-02-10 18:54:02+05:00",
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 2.28971962616822, "non_criminal": 40.0778816199377},
                "male": {"allowed": True, "criminal": 30.4766355140187, "non_criminal": 139.68847352025},
            },
            "source_urls": [
                "https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx",
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=5",
                "https://www.ice.gov/detain/detention-facilities/san-luis-regional-detention-center",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "409 FM 1144,KARNES CITY,TX,78118": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "TX",
                "country": "United States",
                "locality": "Karnes City",
                "postal_code": "78118",
                "street": "409 FM 1144",
            },
            "avg_stay_length": 32.4188289322618,
            "facility_type": "DIGSA",
            "field_office": {
                "address": {
                    "administrative_area": "TX",
                    "country": "United States",
                    "locality": "San Antonio",
                    "postal_code": "78217",
                    "street": "1777 NE Loop 410 Floor 15",
                },
                "address_str": "1777 NE Loop 410 Floor 15 San Antonio, TX 78217",
                "aor": "Central Texas",
                "email": "SanAntonio.Outreach@ice.dhs.gov",
                "field_office": "San Antonio Field Office",
                "name": "San Antonio - ERO",
                "phone": "(210) 283-4750",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=6&exposed_form_display=1"],
            },
            "image_url": "https://www.ice.gov/sites/default/files/images/detention/karnetx_0.jpg",
            "inspection_date": "2025-06-05",
            "name": "KARNES COUNTY IMMIGRATION PROCESSING CENTER",
            "page_updated_date": "2025-08-18 15:00:23+04:00",
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 18.8971962616822, "non_criminal": 254.841121495331},
                "male": {"allowed": True, "criminal": 54.8193146417444, "non_criminal": 617.056074766361},
            },
            "source_urls": [
                "https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx",
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=3",
                "https://www.ice.gov/detain/detention-facilities/karnes-county-ipc",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "451 DOREMUS AVENUE,NEWARK,NJ,07105": {
            "_repaired_record": True,
            "address": {
                "administrative_area": "NJ",
                "country": "United States",
                "locality": "Newark",
                "postal_code": "07105",
                "street": "451 Doremus Avenue",
            },
            "avg_stay_length": 17.4443907156673,
            "facility_type": "CDF",
            "field_office": {
                "address": {
                    "administrative_area": "NJ",
                    "country": "United States",
                    "locality": "Newark",
                    "postal_code": "07102",
                    "street": "970 Broad St. 11th Floor",
                },
                "address_str": "970 Broad St. 11th Floor Newark, NJ 07102",
                "aor": "New Jersey",
                "email": "Newark.Outreach@ice.dhs.gov",
                "field_office": "Newark Field Office",
                "name": "Newark - ERO",
                "phone": "(862) 445-9200",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=4&exposed_form_display=1"],
            },
            "image_url": "https://www.ice.gov/sites/default/files/2025-05/detFacDelaney.png",
            "inspection_date": None,
            "name": "DELANEY HALL DETENTION FACILITY",
            "page_updated_date": "2025-09-04 08:48:58+04:00",
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 1.5607476635514, "non_criminal": 14.1401869158878},
                "male": {"allowed": True, "criminal": 26.8255451713395, "non_criminal": 144.118380062306},
            },
            "source_urls": [
                "https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx",
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=1",
                "https://www.ice.gov/detain/detention-facilities/delaney-hall-detention-facility",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "5001 MALONEYVILLE RD,KNOXVILLE,TN,37918": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "TN",
                "country": "",
                "locality": "KNOXVILLE",
                "postal_code": 37918,
                "street": "5001 MALONEYVILLE RD",
            },
            "avg_stay_length": 3.50472914875322,
            "facility_type": "USMS IGA",
            "field_office": {
                "address": {
                    "administrative_area": "LA",
                    "country": "United States",
                    "locality": "New Orleans",
                    "postal_code": "70113",
                    "street": "1250 Poydras Suite 325",
                },
                "address_str": "1250 Poydras Suite 325 New Orleans, LA 70113",
                "aor": "Alabama, Arkansas, Louisiana, Mississippi, Tennessee",
                "email": "NewOrleans.Outreach@ice.dhs.gov",
                "field_office": "New Orleans Field Office",
                "name": "New Orleans - ERO",
                "phone": "(504) 599-7800",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=4&exposed_form_display=1"],
            },
            "image_url": "",
            "inspection_date": "2024-09-26",
            "name": "KNOX COUNTY DETENTION FACILITY",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 0.682242990654206, "non_criminal": 1.27725856697819},
                "male": {"allowed": True, "criminal": 12.6915887850465, "non_criminal": 11.9968847352023},
            },
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "555 GEO DRIVE,PHILIPSBURG,PA,16866": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "PA",
                "country": "United States",
                "locality": "Philipsburg",
                "postal_code": "16866",
                "street": "555 GEO Drive",
            },
            "avg_stay_length": 60.3703295188198,
            "facility_type": "DIGSA",
            "field_office": {
                "address": {
                    "administrative_area": "PA",
                    "country": "United States",
                    "locality": "Philadelphia",
                    "postal_code": "19107",
                    "street": "114 North 8th Street",
                },
                "address_str": "114 North 8th Street Philadelphia, PA 19107",
                "aor": "Delaware, Pennsylvania, West Virginia",
                "email": "Philadelphia.Outreach@ice.dhs.gov",
                "field_office": "Philadelphia Field Office",
                "name": "Philadelphia - ERO",
                "phone": "(215) 656-7164",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=5&exposed_form_display=1"],
            },
            "image_url": "https://www.ice.gov/assets/pages/detention/facilities/moshannon.png",
            "inspection_date": "2025-03-06",
            "name": "MOSHANNON VALLEY PROCESSING CENTER",
            "page_updated_date": "2025-08-14 07:24:42+04:00",
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 25.7071651090343, "non_criminal": 22.4735202492212},
                "male": {"allowed": True, "criminal": 699.031152647976, "non_criminal": 637.196261682248},
            },
            "source_urls": [
                "https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx",
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=4",
                "https://www.ice.gov/detain/detention-facilities/moshannon-valley-processing-center",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "651 FEDERAL DRIVE SUITE 104,GUAYNABO,PR,965": {
            "_repaired_record": True,
            "address": {
                "administrative_area": "PR",
                "country": "",
                "locality": "GUAYNABO",
                "postal_code": 965,
                "street": "651 FEDERAL DRIVE, SUITE 104",
            },
            "avg_stay_length": 4.94200351493849,
            "facility_type": "STAGING",
            "field_office": {
                "address": {
                    "administrative_area": "FL",
                    "country": "United States",
                    "locality": "Plantation",
                    "postal_code": "33324",
                    "street": "865 SW 78th Avenue Suite 101",
                },
                "address_str": "865 SW 78th Avenue Suite 101 Plantation, FL 33324",
                "aor": "Florida, Puerto Rico, U.S. Virgin Islands",
                "email": "Miami.Outreach@ice.dhs.gov",
                "field_office": "Miami Field Office",
                "name": "Plantation - ERO",
                "phone": "(954) 236-4900",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=5&exposed_form_display=1"],
            },
            "image_url": "",
            "inspection_date": None,
            "name": "SAN JUAN STAGING",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 0.196261682242991, "non_criminal": 1.01869158878505},
                "male": {"allowed": True, "criminal": 3.46105919003115, "non_criminal": 8.28037383177564},
            },
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "6920 DIGITAL RD,EL PASO,TX,79936": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "TX",
                "country": "",
                "locality": "EL PASO",
                "postal_code": 79936,
                "street": "6920 DIGITAL RD",
            },
            "avg_stay_length": 2.1,
            "facility_type": "CDF",
            "field_office": {
                "address": {
                    "administrative_area": "TX",
                    "country": "United States",
                    "locality": "El Paso",
                    "postal_code": "79936",
                    "street": "11541 Montana Ave Suite E",
                },
                "address_str": "11541 Montana Ave Suite E El Paso, TX 79936",
                "aor": "West Texas, New Mexico",
                "email": "ElPaso.Outreach@ice.dhs.gov",
                "field_office": "El Paso Field Office",
                "name": "El Paso - ERO",
                "phone": "(915) 225-1901",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=2&exposed_form_display=1"],
            },
            "image_url": "",
            "inspection_date": None,
            "name": "ERO EL PASO CAMP EAST MONTANA",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 0.0124610591900312, "non_criminal": 0.0186915887850467},
                "male": {"allowed": True, "criminal": 2.09345794392522, "non_criminal": 4.56074766355134},
            },
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "705 HANOVER STREET,HAMILTON,OH,45011": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "OH",
                "country": "United States",
                "locality": "Hamilton",
                "postal_code": "45011",
                "street": "705 Hanover Street",
            },
            "avg_stay_length": 27.7724268177526,
            "facility_type": "USMS IGA",
            "field_office": {
                "address": {
                    "administrative_area": "MI",
                    "country": "United States",
                    "locality": "Detroit",
                    "postal_code": "48226",
                    "street": "985 Michigan Avenue Suite 207",
                },
                "address_str": "985 Michigan Avenue Suite 207 Detroit, MI 48226",
                "aor": "Michigan, Ohio",
                "email": "Detroit.Outreach@ice.dhs.gov",
                "field_office": "Detroit Field Office",
                "name": "Detroit - ERO",
                "phone": "(313) 771-6601",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=1&exposed_form_display=1"],
            },
            "image_url": "https://www.ice.gov/sites/default/files/images/detFacButler.png",
            "inspection_date": None,
            "name": "BUTLER COUNTY JAIL",
            "page_updated_date": "2025-05-15 07:19:46+04:00",
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 1.80685358255452, "non_criminal": 12.0155763239875},
                "male": {"allowed": True, "criminal": 33.5358255451713, "non_criminal": 94.968847352025},
            },
            "source_urls": [
                "https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx",
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=0",
                "https://www.ice.gov/detain/detention-facilities/butler-county-sheriffs-office",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "715 5TH AVENUE,HOLDREGE,NE,68949": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "NE",
                "country": "United States",
                "locality": "Holdrege",
                "postal_code": "68949",
                "street": "715 5th Avenue",
            },
            "avg_stay_length": 38.6484375,
            "facility_type": "USMS IGA",
            "field_office": {
                "address": {
                    "administrative_area": "MN",
                    "country": "United States",
                    "locality": "Fort Snelling",
                    "postal_code": "55111",
                    "street": "1 Federal Drive Suite 1601",
                },
                "address_str": "1 Federal Drive Suite 1601 Fort Snelling, MN 55111",
                "aor": "",
                "email": "StPaul.Outreach@ice.dhs.gov",
                "field_office": "St Paul Field Office",
                "name": "Fort Snelling - ERO",
                "phone": "(612) 843-8600",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=2&exposed_form_display=1"],
            },
            "image_url": "https://www.ice.gov/assets/pages/detention/facilities/phelpsCoJail.jpg",
            "inspection_date": "2025-02-06",
            "name": "PHELPS COUNTY JAIL (NE)",
            "page_updated_date": "2025-02-10 18:50:51+05:00",
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 1.19626168224299, "non_criminal": 0.355140186915888},
                "male": {"allowed": True, "criminal": 23.607476635514, "non_criminal": 5.74454828660436},
            },
            "source_urls": [
                "https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx",
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=4",
                "https://www.ice.gov/detain/detention-facilities/phelps-county-jail",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "CoreCivic Laredo Processing Center": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "TX",
                "country": "United States",
                "locality": "Laredo",
                "postal_code": "78401",
                "street": "4702 East Saunders",
            },
            "avg_stay_length": 0,
            "facility_type": "",
            "field_office": {
                "address": {
                    "administrative_area": "TX",
                    "country": "United States",
                    "locality": "Harlingen",
                    "postal_code": "78552",
                    "street": "1717 Zoy Street",
                },
                "address_str": "1717 Zoy Street Harlingen, TX 78552",
                "aor": "South Texas",
                "email": "Harlingen.Outreach@ice.dhs.gov",
                "field_office": "Harlingen Field Office",
                "name": "Harlingen - ERO",
                "phone": "(956) 389-7884",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=2&exposed_form_display=1"],
            },
            "image_url": "https://www.ice.gov/sites/default/files/images/detention/lrdicdf.jpg",
            "inspection_date": None,
            "name": "CoreCivic Laredo Processing Center",
            "page_updated_date": "2025-02-10 15:38:10+05:00",
            "phone": "",
            "population": {
                "female": {"allowed": False, "criminal": 0, "non_criminal": 0},
                "male": {"allowed": False, "criminal": 0, "non_criminal": 0},
            },
            "source_urls": [
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=1",
                "https://www.ice.gov/detain/detention-facilities/laredo-detention-center",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "DoD Detention Facility at Fort Bliss": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "TX",
                "country": "United States",
                "locality": "El Paso",
                "postal_code": "79936",
                "street": "11541 Montana Avenue",
            },
            "avg_stay_length": 0,
            "facility_type": "",
            "field_office": {
                "address": {
                    "administrative_area": "TX",
                    "country": "United States",
                    "locality": "El Paso",
                    "postal_code": "79936",
                    "street": "11541 Montana Ave Suite E",
                },
                "address_str": "11541 Montana Ave Suite E El Paso, TX 79936",
                "aor": "West Texas, New Mexico",
                "email": "ElPaso.Outreach@ice.dhs.gov",
                "field_office": "El Paso Field Office",
                "name": "El Paso - ERO",
                "phone": "(915) 225-1901",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=2&exposed_form_display=1"],
            },
            "image_url": "https://www.ice.gov/sites/default/files/2025-09/detFacFortBliss.jpg",
            "inspection_date": None,
            "name": "DoD Detention Facility at Fort Bliss",
            "page_updated_date": "2025-09-02 14:01:55+04:00",
            "phone": "",
            "population": {
                "female": {"allowed": False, "criminal": 0, "non_criminal": 0},
                "male": {"allowed": False, "criminal": 0, "non_criminal": 0},
            },
            "source_urls": [
                "https://www.ice.gov/detention-facilities?exposed_form_display=1&page=1",
                "https://www.ice.gov/detain/detention-facilities/dod-detention-facility-fort-bliss",
            ],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
        "PARK STREET,FONDA,NY,12068": {
            "_repaired_record": False,
            "address": {
                "administrative_area": "NY",
                "country": "",
                "locality": "FONDA",
                "postal_code": 12068,
                "street": "PARK STREET",
            },
            "avg_stay_length": 1.95475113122172,
            "facility_type": "IGSA",
            "field_office": {
                "address": {
                    "administrative_area": "NY",
                    "country": "United States",
                    "locality": "Buffalo",
                    "postal_code": "14202",
                    "street": "250 Delaware Avenue, Floor 7",
                },
                "address_str": "250 Delaware Avenue, Floor 7 Buffalo, NY 14202",
                "aor": "Upstate New York",
                "email": "Buffalo.Outreach@ice.dhs.gov",
                "field_office": "Buffalo Field Office",
                "name": "Buffalo - ERO",
                "phone": "(716) 464-5800",
                "source_urls": ["https://www.ice.gov/contact/field-offices?page=0&exposed_form_display=1"],
            },
            "image_url": "",
            "inspection_date": None,
            "name": "MONTGOMERY COUNTY JAIL",
            "page_updated_date": None,
            "phone": "",
            "population": {
                "female": {"allowed": True, "criminal": 0.0, "non_criminal": 0.0685358255451713},
                "male": {"allowed": True, "criminal": 0.286604361370716, "non_criminal": 1.06853582554517},
            },
            "source_urls": ["https://www.ice.gov/doclib/detention/FY25_detentionStats08292025.xlsx"],
            "wikipedia": {
                "page_url": "",
                "search_query": "",
            },
            "wikidata": {
                "page_url": "",
                "search_query": "",
            },
            "osm": {
                "url": "",
                "latitude": "38.89511000",
                "longitude": "-77.03637000",
                "search_query": "",
            },
        },
    },
    "scrape_runtime": 48.883458614349365,
    "scraped_date": "2025-09-08 00:00:17.837345",
}
